swagger: "2.0"
info:
  description: This is the Open API specification of the Burdock execution service.
  version: "0.0.1"
  title: Swagger ReST Article
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /execute:
    post:
      operationId: execute.run
      tags:
        - execute
      summary: Execute a differentially private module
      description: Create a run of the specified module and return the results.
      parameters:
        - name: details
          in: body
          description: Configuration for the module run.
          required: True
          schema:
            $ref: '#/definitions/ProjectRunDetails'
      responses:
        200:
          description: Successfully executed the run
          schema:
            $ref: '#/definitions/ExecuterunOKResponse'
  /dataset:
    post:
      operationId: dataset.read
      tags:
        - datasetRead
      summary: Read the details for reading the dataset
      description: Return the details of the requested dataset
      parameters:
        - name: dataset_request
          in: body
          description: Get the dataset read request
          required: True
          schema:
            $ref: '#/definitions/DatasetReadRequest'
      responses:
         200:
           description: Successfully return the dataset information
           schema:
            $ref: '#/definitions/DatasetDocument'
  /register:
    post:
      operationId: dataset.register
      tags:
        - datasetRegister
      summary: Register a new dataset with budget
      description: Posts dataset info, creates new entry in remote dict
      parameters:
        - name: dataset
          in: body
          description: Well formed dataset for adding to dict
          required: True
          schema:
            $ref: '#/definitions/DatasetDocument'
      responses:
         200:
           description: Successfully registered a new dataset
           schema:
            $ref: '#/definitions/RegisterOKResponse'
  /secrets:
    post:
      operationId: secrets.put
      tags:
        - addSecret
      summary: Add a secret to the secret store
      description: Add the secret to the secret store
      parameters:
        - name: secret
          in: body
          description: Add a secret
          required: True
          schema:
            $ref: '#/definitions/Secret'
      responses:
         200:
           description: Successfully added the secret
           schema:
            $ref: '#/definitions/SecretPutSuccess'

definitions:
  ProjectRunDetails:
    type: object
    properties:
      project_uri:
        type: string
        description: Git url of the project
      params:
        type: string
        description: Input parameters of the project
  DatasetReadRequest:
    type: object
    properties:
      dataset_name:
        type: string
        description: The name for the dataset
      budget:
        type: number
        format: float
        description: Budget used by this read request
  LocalCSVDetails:
    type: object
    properties:
      local_path:
        type: string
        description: Path to the csv on disk
  DataverseDetails:
    type: object
    properties:
      local_metadata_path:
        type: string
      host:
        type: string
        description: Host of dataset, if dataverse
      token:
        type: string
        description: The token for the dataverse
      schema:
        type: string
        description: Schema of dataset, well formed json
  DatasetDocument:
    type: object
    properties:
      dataset_name:
        type: string
        description: The name for the dataset
      dataset_type:
        type: string
        description: The type of the dataset
      budget:
        type: number
        format: float
        description: Available budget for the dataset registered
      csv_details:
        $ref: '#/definitions/LocalCSVDetails'
      dataverse_details:
        $ref: '#/definitions/DataverseDetails'
  Secret:
    type: object
    properties:
      name:
        type: string
        description: The name of the secret
      value:
        type: string
        description: The secret
  SecretPutSuccess:
    type: object
    properties:
      name:
        type: string
        description: The name of the secret
  ExecuterunOKResponse:
    type: object
    properties:
      result:
        type: string
        description: Json string result,  TODO release document
  RegisterOKResponse:
    type: object
    properties:
      result:
        type: string
        description: DatasetName

